### ISSUE TITLE
Doesn't work on 46.2

### ISSUE THREAD

**Issue by ashkanak** [spiridonkopicl/evrybo-sketch-plugin#1]
Hi there,

The plugin doesnt work on Sketch 46.2

**Comment by spiridonkopicl** [comment]
Hi @ashkanak ,
 
can you provide me with more details. Login, export or at all it is not working ?

Can you do me a favor and start the console.app and there in search field choose for process: sketch and for library: sketch. You should clear the content in console.app. Start the Sketch and try to login from plugin, and then export. And then see the log in console.app and provide it to me as screenshot. That would be very helpful. 

Thanks.

**Comment by ashkanak** [comment]
Hi @spiridonkopicl,

Thanks for the swift response!
Here is the issue listed from Console.app


19/10/17 5:28:26.662 PM Login / Logout (Sketch)[800]: SyntaxError: Unexpected identifier 'errorResponse'.
Plugin “login”, line 522:
»         let errorResponse = service.login(email, password)
19/10/17 5:28:26.663 PM Sketch[800]: Exception: {
    line = 522;
    sourceURL = "/Users/Ashkan/Library/Application Support/com.bohemiancoding.sketch3/Plugins/evrybo.sketchplugin/Contents/Sketch/login.js";
    stack = undefined;
}
19/10/17 5:31:08.189 PM Sketch[800]: Loading message with version: https://api.magicsketch.io/r/get_messages?version=3.0.6.28&skVersion=46.2.44496&osVersion=10.11.6

**Comment by ashkanak** [comment]
19/10/17 5:31:08.189 PM Sketch[800]: Loading message with version: https://api.magicsketch.io/r/get_messages?version=3.0.6.28&skVersion=46.2.44496&osVersion=10.11.6

**Comment by ashkanak** [comment]
I am trying to find evrybo.com email address to send you guys few ideas and suggestions but I can not find any contact in any form! Do you have anyone's contact to hear my ideas?

**Comment by spiridonkopicl** [comment]
Of course. Thx. You can write on support@evrybo.com

**Comment by spiridonkopicl** [comment]
hi @ashkanak,

can you please download this working version [evrybo.sketchplugin.zip](https://github.com/spiridonkopicl/evrybo-sketch-plugin/files/1401787/evrybo.sketchplugin.zip), unzip it and install plugin. I fixed some issue, can you please test it and give me a feedback. Really appreciate your time.

**Comment by ashkanak** [comment]
Frist of all thanks for being awesome and creating such a cool product for free.


I uninstalled the plugin manually and reinstalled from the above link but It seems its the same version 1.0.1 and still gets the blow errors in console. 

21/10/17 9:47:27.218 AM Login / Logout (Sketch)[756]: SyntaxError: Unexpected identifier 'ns_httpUrlResponse'.
Plugin “login”, line 287:
»         let ns_httpUrlResponse = response.value()
21/10/17 9:47:27.219 AM Sketch[756]: Exception: {
    line = 287;
    sourceURL = "/Users/Ashkan/Library/Application Support/com.bohemiancoding.sketch3/Plugins/evrybo.sketchplugin/Contents/Sketch/login.js";
    stack = undefined;
}

**Comment by spiridonkopicl** [comment]
Yep the version is same, it wasn't updated.

This error occurs when you uploading artboards. So login is working for you now, when you are able to upload the artboards ? (that was previous issue, so I assume that is fixed :) )

I will attach here a new version, so you can test it again. Sorry but there is no way that I can reproduce it in local, so please you should provide me the log. Please look for: '[INFO][evrybo] uploadArtboards: ' in the console.app and send me the log. Really appreciate.
[evrybo.sketchplugin.zip](https://github.com/spiridonkopicl/evrybo-sketch-plugin/files/1403885/evrybo.sketchplugin.zip)

**Comment by ashkanak** [comment]
I am still facing the same issue, cannot log in. nothing happens when I click on login/logout in plugins drop-down menu. 

This is same error I get in console:
21/10/17 7:54:05.710 PM Login / Logout (Sketch)[756]: SyntaxError: Unexpected identifier 'ns_httpUrlResponse'.
Plugin “login”, line 287:
»         let ns_httpUrlResponse = response.value()
21/10/17 7:54:05.711 PM Sketch[756]: Exception: {
    line = 287;
    sourceURL = "/Users/Ashkan/Library/Application Support/com.bohemiancoding.sketch3/Plugins/evrybo.sketchplugin/Contents/Sketch/login.js";
    stack = undefined;
}

**Comment by spiridonkopicl** [comment]
That is not possible, seems like previous version. Please download this:[evrybo.sketchplugin.zip](https://github.com/spiridonkopicl/evrybo-sketch-plugin/files/1404256/evrybo.sketchplugin.zip) and unzip it and install, restart Sketch, try to login from plugin. In console.app you will see logs like '[INFO][evrybo] login response  ', please copy those and send it to me. Thanks.

**Comment by ashkanak** [comment]
I installed the 1.0.2 version but I still get the same error when I click on login/logout.

22/10/17 7:49:36.949 AM Login / Logout (Sketch)[951]: SyntaxError: Unexpected identifier 'project'.
Plugin “login”, line 485:
»        let project = projects[0];
22/10/17 7:49:36.949 AM Sketch[951]: Exception: {
    line = 485;
    sourceURL = "/Users/Ashkan/Library/Application Support/com.bohemiancoding.sketch3/Plugins/evrybo 2.sketchplugin/Contents/Sketch/login.js";
    stack = undefined;
}
22/10/17 7:49:39.497 AM Sketch[951]: [POST] https://api.animaapp.com/users/me/promotions/


When I click on upload artworks I get following error:
22/10/17 7:50:36.553 AM Sync All Artboards to Evrybo (Sketch)[951]: SyntaxError: Unexpected identifier 'project'.
Plugin “exportAllArtboards”, line 485:
»        let project = projects[0];

**Comment by spiridonkopicl** [comment]
To be honest I am a little bit confused since the second case you mentioned is not possible to be executed - export, since your are not logged in, form with login should shown app. Can you please fallow my previous comment, try to log in and paste mi here the log from console.app which starts with: '[INFO][evrybo] login response'. Search for this in console.app. Also before try to log out, and delete the old version of plugin, install version from previous comment, and afterwards restart sketch. Thx.

**Comment by ashkanak** [comment]
I repeat the above steps again but I still get only 2 logged error from Sketch which is related to everybo login in the console.app. The problem is that the login screen doesn't show up at all, or better to say nothing happens when I click on login but the below error logs in console app.

24/10/17 9:14:50.732 AM Login / Logout (Sketch)[3500]: SyntaxError: Unexpected identifier 'project'.
Plugin “login”, line 485:
»        let project = projects[0];
24/10/17 9:14:50.733 AM Sketch[3500]: Exception: {
    line = 485;
    sourceURL = "/Users/Ashkan/Library/Application Support/com.bohemiancoding.sketch3/Plugins/evrybo 2.sketchplugin/Contents/Sketch/login.js";
    stack = undefined;
}
